version: "3.7"
services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - 5001:5001
    stdin_open: true
    # environment:
    #     - PORT=5001
      # - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - express-redis

  nginx:
    build:
      context: .
    container_name: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - server
    networks:
      - express-redis

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    container_name: redis
    restart: always
    networks:
      - express-redis

networks:
  express-redis:
  